runtime: python

entrypoint: gunicorn -b :$PORT cropper.wsgi
env: flex

env_variables:
  SECRET_KEY: 'nj^r!!0j*85m(=6o)i7iz!n6q=p@a8=0i91zc%!2%o4@1-w^na'
  DEBUG: 'False'
  
  DB_HOST: '/cloudsql/simple-django-image-cropper:us-central1:simple-django-image-cropper-db'
  DB_PORT: '5432'
  DB_NAME: 'image_cropper'
  DB_USER: 'karangu'
  DB_PASSWORD: 'lmzongolo8754'

  MEDIA_BUCKET_NAME: 'simple-django-image-cropper-media'

  STATIC_BUCKET_NAME: 'simple-django-image-cropper-static'
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto


beta_settings:
  cloud_sql_instances: simple-django-image-cropper:us-central1:simple-django-image-cropper-db

runtime_config:
  python_version: 3
